name: Deploy Vite/React Site

on:
  # Roda em todos os pushes para a branch principal (master)
  push:
    branches: ["master"]

  # Permite rodar manualmente
  workflow_dispatch:

# Define as permissões necessárias
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy por vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job 1: Build (Compilação)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 1. Configura o Node.js e o cache
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          cache: 'npm' 

      # 2. Instala todas as dependências (incluindo Tailwind e PostCSS)
      - name: Install Dependencies
        run: npm install

      # 3. Roda o Build (Cria a pasta 'dist' com o Tailwind compilado)
      - name: Run Vite Build
        run: npm run build
      
      # 4. Configura as Páginas
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 5. Prepara o artefato de deploy (a pasta dist)
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # É CRUCIAL que o path seja a pasta de saída do build do Vite
          path: './dist' 

  # Job 2: Deploy (Publicação)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Garante que só roda se o build foi concluído com sucesso
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
