name: Deploy Vite/React Site

on:
  # Roda em todos os pushes para a branch principal (master)
  push:
    branches: ["master"]

  # Permite rodar manualmente
  workflow_dispatch:

# Define as permissões necessárias
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy por vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job 1: Build (Compilação)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' # MUDANÇA PARA OBRIGAR O USO DA VERSÃO COMPATÍVEL
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      # CORREÇÃO: Usar o script estável do package.json (que agora é 'npx vite build')
      - name: Run Vite Build
        run: npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' 

  # Job 2: Deploy (Publicação)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Garante que só roda se o build foi concluído com sucesso
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
